Update detection.py
TDPS-Mihotel/Mihotel pull request #108
Opened 2020-05-24 14:55 UTC by HandAdam

Bridge Detetcion is added

2020-05-24 17:18 UTC, LeoJhonSong requested changes

2020-05-24 17:18 UTC, LeoJhonSong commented on detection.py
> +        image_gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
我看到前面`path_detection()`里你已经改成BGR了, 这里为啥用的RGB呀? `get_image()`里已经转成BGR了吧

2020-05-24 17:18 UTC, LeoJhonSong commented on detection.py
> +        cv2.waitKey(1)
就只是说一下, 我在path_detection里放了个这句是为了imshow能显示出图片, 不知道是不是多进程的原因没有这个显示有问题. 如果你没有想显示图片的话这句话不是必要的.

2020-05-24 17:18 UTC, LeoJhonSong commented on detection.py
> +                        A[i,j] = 1
你这啥啊... 要去噪点的话opencv提供了膨胀和腐蚀函数可用. 你可以参考[这个链接](https://blog.csdn.net/sunny2038/article/details/9137759). 另外后面既然是统计的值为0的点228行和229行很累赘, 直接切片掉就是了.

2020-05-24 17:18 UTC, LeoJhonSong commented on detection.py
> +            mid=64
不要在你这个函数里用依赖于摄像头数据的量. 想表达中间用`A.shape[1] // 2`就好了.

2020-05-24 17:18 UTC, LeoJhonSong commented on detection.py
> +            if np.abs(f_x-mid)<=1:
阈值框也不要以绝对差来, 比如:
```python
x_range = 0.02
if np.abs(f_x - A.shape[1] // 2) <= x_range * A.shape[1]:
```

2020-05-24 17:27 UTC, LeoJhonSong commented
不是, 哥, 你拿啥写的呀... 如果你拿VSC写的你应该看到的和我是差不多的
![image](https://user-images.githubusercontent.com/37630203/82760564-c9cfb500-9e26-11ea-9a23-9d4c194221a4.png)
就算你没有这些蓝色波浪线和红块块, 你也该有红色波浪线吧... 右边小地图可以看到前后还有好几处.
另外明明之前你都是能很好地遵循下划线命名法的怎么这个函数的变量名都是全小写的. 这是一种很不好的命名方式.

2020-05-24 17:29 UTC, LeoJhonSong commented on detection.py
> +        A = np.zeros(shape=[128,128])
不要用这种无意义的变量名.

2020-05-24 17:32 UTC, LeoJhonSong commented on detection.py
> +        A[image_gray>153] = 1
opencv提供了根据阈值二值化的函数.

2020-05-25 00:21 UTC, HandAdam commented on detection.py
> +        image_gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
我试了RGB和BGR，竟然都能用。同理，我把path detection改成RGB，也能够检查到path。

2020-05-25 00:22 UTC, HandAdam commented on detection.py
> +        cv2.waitKey(1)
好，那我改一下

2020-05-25 00:25 UTC, HandAdam commented on detection.py
> +            mid=64
好，我改一下

2020-05-25 00:27 UTC, HandAdam commented on detection.py
> +            if np.abs(f_x-mid)<=1:
好，我改一下

2020-05-25 00:30 UTC, HandAdam commented on detection.py
> +        A = np.zeros(shape=[128,128])
A改成binary_map了

2020-05-25 00:31 UTC, HandAdam commented on detection.py
> +        A[image_gray>153] = 1
就先用这个吧

2020-05-25 04:44 UTC, LeoJhonSong approved these changes
Great! :tada:

2020-05-25 04:45 UTC, merged